# This file stores configurations for your Shopify app.

scopes = "read_themes,write_themes,read_products,write_products,read_product_listings,read_orders,write_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customers,write_customers,read_draft_orders,write_draft_orders,read_inventory,write_inventory"
